Repository Team-Gravit/gravit-server, pull requests merged in 2025-09, with the labels that each got.

#108 hotfix: application.yml 에 누락된 설정 추가
  src/main/resources/application-prod.yml
Labels: 🔥 HotFix

#110 hotfix: cd 파일 수정
  .github/workflows/cd.yml
Labels: 🔥 HotFix

#112 feat: nickname, handle 로 동적 친구 검색 기능 추가
  src/main/java/gravit/code/domain/friend/controller/FriendSearchController.java
  src/main/java/gravit/code/domain/friend/dto/SearchPlan.java
  src/main/java/gravit/code/domain/friend/dto/SearchUser.java
  src/main/java/gravit/code/domain/friend/dto/response/PageSearchUserResponse.java
  src/main/java/gravit/code/domain/friend/infrastructure/FriendSearchRepository.java
  src/main/java/gravit/code/domain/friend/infrastructure/sql/FriendsHandleCountQuerySql.java
  src/main/java/gravit/code/domain/friend/infrastructure/sql/FriendsHandleSearchQuerySql.java
  src/main/java/gravit/code/domain/friend/infrastructure/sql/FriendsNicknameCountQuerySql.java
  src/main/java/gravit/code/domain/friend/infrastructure/sql/FriendsNicknameSearchQuerySql.java
  src/main/java/gravit/code/domain/friend/infrastructure/strategy/FriendsSearchFactory.java
  src/main/java/gravit/code/domain/friend/infrastructure/strategy/FriendsSearchStrategy.java
  src/main/java/gravit/code/domain/friend/infrastructure/strategy/HandleSearchStrategy.java
  src/main/java/gravit/code/domain/friend/infrastructure/strategy/NicknameSearchStrategy.java
  src/main/java/gravit/code/domain/friend/service/FriendSearchService.java
  src/main/java/gravit/code/domain/friend/util/QueryNormalizeUtil.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/main/resources/db/migration/seed/V8__seed_user_leagues.sql
Labels: 🌼 Feat

#127 feat: 유저 삭제 플로우(이메일 인증) 추가
  .github/workflows/cd.yml
  build.gradle
  docker-compose.local.yml
  docker-compose.yml
  src/main/java/gravit/code/GravitApplication.java
  src/main/java/gravit/code/auth/oauth/service/OAuthClientService.java
  src/main/java/gravit/code/auth/oauth/service/OAuthLoginUrlService.java
  src/main/java/gravit/code/global/config/MailConfig.java
  src/main/java/gravit/code/global/config/PropsConfig.java
  src/main/java/gravit/code/global/config/RedisConfig.java
  src/main/java/gravit/code/global/config/SecurityConfig.java
  src/main/java/gravit/code/global/consts/RedirectHostConst.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/main/java/gravit/code/user/config/UserDeleteMailProps.java
  src/main/java/gravit/code/user/controller/UserController.java
  src/main/java/gravit/code/user/controller/UserDeletionController.java
  src/main/java/gravit/code/user/controller/docs/UserControllerDocs.java
  src/main/java/gravit/code/user/controller/docs/UserDeletionControllerSpecification.java
  src/main/java/gravit/code/user/domain/User.java
  src/main/java/gravit/code/user/domain/UserLevel.java
  src/main/java/gravit/code/user/domain/UserRepository.java
  src/main/java/gravit/code/user/domain/UserStatus.java
  src/main/java/gravit/code/user/infrastructure/RedisMailAuthCodeStore.java
  src/main/java/gravit/code/user/infrastructure/StmpMailSender.java
  src/main/java/gravit/code/user/infrastructure/UserJpaRepository.java
  src/main/java/gravit/code/user/infrastructure/UserRepositoryImpl.java
  src/main/java/gravit/code/user/service/UserDeletionService.java
  src/main/java/gravit/code/user/service/UserService.java
  src/main/java/gravit/code/user/service/port/MailAuthCodeStore.java
  src/main/java/gravit/code/user/service/port/MailSender.java
  src/main/java/gravit/code/user/util/MailAuthCodeGenerator.java
  src/main/java/gravit/code/user/util/MailHtmlRenderer.java
  src/main/java/gravit/code/user/util/RedisMailAuthCodeConstants.java
  src/main/resources/application-prod.yml
  src/main/resources/db/learning_data.sql
  src/main/resources/db/migration/V12__users_soft_delete_and_status.sql
  src/main/resources/db/migration/V1__init_tables.sql
  src/test/java/gravit/code/user/domain/UserRepositoryTest.java
  src/test/java/gravit/code/user/domain/UserTest.java
  src/test/java/gravit/code/user/util/MailAuthCodeGeneratorTest.java
  src/test/java/gravit/code/userLeague/listener/LessonCompletedListenerTest.java
  src/test/resources/application-test.yml
Labels: 🌼 Feat

#147 feat: 뱃지 도메인 추가
  src/main/java/gravit/code/auth/jwt/JwtAuthFilter.java
  src/main/java/gravit/code/badge/controller/BadgeQueryController.java
  src/main/java/gravit/code/badge/controller/docs/BadgeQueryControllerDocs.java
  src/main/java/gravit/code/badge/converter/JsonNodeConverter.java
  src/main/java/gravit/code/badge/domain/Badge.java
  src/main/java/gravit/code/badge/domain/BadgeCategory.java
  src/main/java/gravit/code/badge/domain/BadgeType.java
  src/main/java/gravit/code/badge/domain/CriteriaType.java
  src/main/java/gravit/code/badge/domain/Planet.java
  src/main/java/gravit/code/badge/domain/user/UserBadge.java
  src/main/java/gravit/code/badge/domain/user/UserMissionStat.java
  src/main/java/gravit/code/badge/domain/user/UserPlanetCompletion.java
  src/main/java/gravit/code/badge/domain/user/UserQualifiedSolveStat.java
  src/main/java/gravit/code/badge/dto/BadgeCatalogRowDto.java
  src/main/java/gravit/code/badge/dto/MissionCompleteDto.java
  src/main/java/gravit/code/badge/dto/PlanetCompletionDto.java
  src/main/java/gravit/code/badge/dto/QualifiedSolveCountDto.java
  src/main/java/gravit/code/badge/dto/response/AllBadgesResponse.java
  src/main/java/gravit/code/badge/dto/response/BadgeCategoryResponse.java
  src/main/java/gravit/code/badge/dto/response/BadgeResponse.java
  src/main/java/gravit/code/badge/infrastructure/BadgeCategoryRepository.java
  src/main/java/gravit/code/badge/infrastructure/BadgeRepository.java
  src/main/java/gravit/code/badge/infrastructure/user/UserBadgeRepository.java
  src/main/java/gravit/code/badge/infrastructure/user/UserMissionStatRepository.java
  src/main/java/gravit/code/badge/infrastructure/user/UserPlanetCompletionRepository.java
  src/main/java/gravit/code/badge/infrastructure/user/UserQualifiedSolveStatRepository.java
  src/main/java/gravit/code/badge/listener/BadgeEventListener.java
  src/main/java/gravit/code/badge/service/BadgeGrantService.java
  src/main/java/gravit/code/badge/service/BadgeQueryService.java
  src/main/java/gravit/code/badge/service/ProjectionService.java
  src/main/java/gravit/code/badge/test/TestEventController.java
  src/main/java/gravit/code/global/config/AsyncConfig.java
  src/main/java/gravit/code/global/config/SecurityConfig.java
  src/main/java/gravit/code/global/event/badge/MissionCompletedEvent.java
  src/main/java/gravit/code/global/event/badge/PlanetCompletedEvent.java
  src/main/java/gravit/code/global/event/badge/QualifiedSolvedEvent.java
  src/main/java/gravit/code/global/event/badge/StreakUpdatedEvent.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/main/java/gravit/code/learning/domain/Learning.java
  src/main/java/gravit/code/learning/dto/StreakDto.java
  src/main/java/gravit/code/learning/facade/LearningFacade.java
  src/main/java/gravit/code/learning/listener/LearningEventListener.java
  src/main/java/gravit/code/mission/service/MissionService.java
  src/main/java/gravit/code/progress/domain/ChapterProgress.java
  src/main/java/gravit/code/progress/dto/ChapterCompletedDto.java
  src/main/java/gravit/code/progress/service/ChapterProgressService.java
  src/main/resources/db/migration/V16__create_badge_table.sql
  src/main/resources/db/migration/seed/V17__seed_badge.sql
  src/test/java/gravit/code/progress/service/ChapterProgressServiceTest.java
  src/test/resources/logback-test.xml
Labels: 🌼 Feat

#165 fix: 환경변수명 수정 (#157)
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: 🚦CICD

#188 fix: api 테스트 중 발생한 에러 해결 및 개선 방안 적용
  src/main/java/gravit/code/admin/controller/AdminNoticeCommandController.java
  src/main/java/gravit/code/admin/controller/AdminNoticeQueryController.java
  src/main/java/gravit/code/admin/controller/docs/AdminNoticeCommandControllerDocs.java
  src/main/java/gravit/code/admin/controller/docs/AdminNoticeQueryControllerDocs.java
  src/main/java/gravit/code/admin/dto/response/AdminNoticeDetailResponse.java
  src/main/java/gravit/code/admin/dto/response/AdminNoticeSummaryResponse.java
  src/main/java/gravit/code/admin/service/AdminNoticeCommandService.java
  src/main/java/gravit/code/admin/service/AdminNoticeQueryService.java
  src/main/java/gravit/code/friend/controller/FriendController.java
  src/main/java/gravit/code/friend/controller/docs/FriendControllerDocs.java
  src/main/java/gravit/code/friend/controller/docs/FriendSearchControllerDocs.java
  src/main/java/gravit/code/friend/domain/FriendRepository.java
  src/main/java/gravit/code/friend/dto/FollowCountsResponse.java
  src/main/java/gravit/code/friend/dto/response/PageSearchUserResponse.java
  src/main/java/gravit/code/friend/infrastructure/FriendJpaRepository.java
  src/main/java/gravit/code/friend/infrastructure/FriendRepositoryImpl.java
  src/main/java/gravit/code/friend/infrastructure/strategy/HandleSearchStrategy.java
  src/main/java/gravit/code/friend/infrastructure/strategy/NicknameSearchStrategy.java
  src/main/java/gravit/code/friend/service/FriendSearchService.java
  src/main/java/gravit/code/friend/service/FriendService.java
  src/main/java/gravit/code/friend/support/HandleNormalize.java
  src/main/java/gravit/code/friend/support/NicknameNormalize.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/main/java/gravit/code/learning/controller/LearningController.java
  src/main/java/gravit/code/learning/controller/docs/LearningControllerDocs.java
  src/main/java/gravit/code/learning/dto/response/LearningResultSaveResponse.java
  src/main/java/gravit/code/learning/facade/LearningFacade.java
  src/main/java/gravit/code/mission/service/MissionService.java
  src/main/java/gravit/code/notice/dto/response/NoticeDetailResponse.java
  src/main/java/gravit/code/notice/infrastructure/NoticeRepository.java
  src/main/java/gravit/code/notice/service/NoticeQueryService.java
  src/main/java/gravit/code/progress/domain/ChapterProgress.java
  src/main/java/gravit/code/progress/service/ChapterProgressService.java
  src/main/java/gravit/code/report/domain/Report.java
  src/main/java/gravit/code/report/service/ReportService.java
  src/main/java/gravit/code/season/batch/SeasonBatchService.java
  src/main/java/gravit/code/security/config/SecurityConfig.java
  src/main/java/gravit/code/userLeague/service/UserLeagueService.java
  src/main/java/gravit/code/userLeagueHistory/infrastructure/UserLeagueHistoryRepository.java
  src/test/java/gravit/code/friend/infrastructure/FriendSearchRepositoryTest.java
  src/test/java/gravit/code/learning/controller/LearningControllerTest.java
  src/test/java/gravit/code/learning/facade/LearningFacadeTest.java
  src/test/java/gravit/code/report/service/ReportServiceTest.java
  src/test/java/gravit/code/season/batch/SeasonBatchServiceTest.java
  src/test/resources/application-test.yml
Labels: 🔨 Fix

#194 Hotfix/193 badge description
  src/main/java/gravit/code/badge/domain/BadgeCategory.java
  src/main/java/gravit/code/badge/dto/BadgeCatalogRowDto.java
  src/main/java/gravit/code/badge/dto/response/BadgeCategoryResponse.java
  src/main/java/gravit/code/badge/infrastructure/BadgeRepository.java
  src/main/java/gravit/code/badge/service/BadgeQueryService.java
  src/main/resources/db/migration/V20__add_badge_category_description.sql
Labels: 🔥 HotFix
