Repository Team-Gravit/gravit-server, pull requests merged in 2025-08, with the labels that each got.

#36 test: Auth, User, Friend 테스트 코드 추가
  .github/workflows/ci.yml
  src/main/java/gravit/code/auth/jwt/JwtAuthFilter.java
  src/main/java/gravit/code/auth/jwt/JwtProvider.java
  src/main/java/gravit/code/auth/oauth/controller/OAuthController.java
  src/main/java/gravit/code/auth/oauth/controller/docs/OAuthControllerDocs.java
  src/main/java/gravit/code/auth/oauth/dto/AuthCodeRequest.java
  src/main/java/gravit/code/auth/oauth/processor/OAuthLoginProcessor.java
  src/main/java/gravit/code/auth/oauth/service/OAuthClientService.java
  src/main/java/gravit/code/auth/oauth/service/WebClientAdapter.java
  src/main/java/gravit/code/auth/util/HandleGenerator.java
  src/main/java/gravit/code/auth/util/RandomHandleGenerator.java
  src/main/java/gravit/code/domain/friend/controller/FriendController.java
  src/main/java/gravit/code/domain/friend/controller/docs/FriendControllerDocs.java
  src/main/java/gravit/code/domain/friend/domain/Friend.java
  src/main/java/gravit/code/domain/friend/dto/response/FollowerResponse.java
  src/main/java/gravit/code/domain/friend/dto/response/FollowingResponse.java
  src/main/java/gravit/code/domain/friend/infrastructure/FriendJpaRepository.java
  src/main/java/gravit/code/domain/friend/service/FriendService.java
  src/main/java/gravit/code/domain/user/controller/UserController.java
  src/main/java/gravit/code/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/gravit/code/domain/user/domain/User.java
  src/main/java/gravit/code/domain/user/dto/request/OnboardingRequest.java
  src/main/java/gravit/code/domain/user/dto/response/UserResponse.java
  src/main/java/gravit/code/domain/user/service/UserService.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/test/java/gravit/code/auth/jwt/JwtProviderTest.java
  src/test/java/gravit/code/auth/oauth/processor/OAuthLoginProcessorTest.java
  src/test/java/gravit/code/auth/oauth/service/OAuthClientServiceTest.java
  src/test/java/gravit/code/auth/oauth/service/OAuthLoginUrlServiceTest.java
  src/test/java/gravit/code/auth/util/RandomHandleGeneratorTest.java
  src/test/java/gravit/code/domain/friend/controller/FriendControllerTest.java
  src/test/java/gravit/code/domain/friend/service/FriendServiceTest.java
  src/test/java/gravit/code/domain/user/controller/UserControllerTest.java
  src/test/java/gravit/code/domain/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
  src/test/resources/sql/truncate_all.sql
Labels: 🔨 Fix, 🙆🏻‍♂️ Test

#40 hotfix: 배포 서버에서 oauth 로그인 실패 문제로 cors 설정 추가 및 누락된 OauthControllerDocs 추가
  src/main/java/gravit/code/auth/oauth/controller/OAuthController.java
  src/main/java/gravit/code/auth/oauth/controller/docs/OAuthControllerDocs.java
  src/main/java/gravit/code/global/config/SecurityConfig.java
Labels: 🔥 HotFix

#43 chore: swagger 명세 수정 및 피드백 반영
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  src/main/java/gravit/code/auth/oauth/controller/docs/OAuthControllerDocs.java
  src/main/java/gravit/code/domain/chapterProgress/infrastructure/ChapterProgressRepositoryImpl.java
  src/main/java/gravit/code/domain/chapterProgress/service/ChapterProgressService.java
  src/main/java/gravit/code/domain/friend/controller/docs/FriendControllerDocs.java
  src/main/java/gravit/code/domain/learning/controller/LearningController.java
  src/main/java/gravit/code/domain/learning/controller/docs/LearningControllerSpecification.java
  src/main/java/gravit/code/domain/lessonProgress/infrastructure/LessonProgressRepositoryImpl.java
  src/main/java/gravit/code/domain/lessonProgress/service/LessonProgressService.java
  src/main/java/gravit/code/domain/mainPage/controller/MainPageController.java
  src/main/java/gravit/code/domain/mainPage/controller/docs/MainPageControllerSpecification.java
  src/main/java/gravit/code/domain/problem/service/ProblemService.java
  src/main/java/gravit/code/domain/recentLearning/service/RecentLearningEventHandler.java
  src/main/java/gravit/code/domain/recentLearning/service/RecentLearningService.java
  src/main/java/gravit/code/domain/unitProgress/infrastructure/UnitProgressJpaRepository.java
  src/main/java/gravit/code/domain/user/controller/UserController.java
  src/main/java/gravit/code/domain/user/controller/docs/UserControllerDocs.java
  src/main/java/gravit/code/domain/user/service/UserService.java
  src/main/java/gravit/code/global/config/SecurityConfig.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/main/java/gravit/code/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/gravit/code/domain/chapterProgress/service/ChapterProgressServiceTest.java
  src/test/java/gravit/code/domain/learning/controller/LearningControllerTest.java
  src/test/java/gravit/code/domain/learning/facade/LearningFacadeTest.java
Labels: 📚 Docs, 🧹Refactor

#50 fix: 리뷰 달린 내용 반영 + JpaAuditing 중복으로 인해 Test 에러 해결
  src/main/java/gravit/code/GravitApplication.java
  src/main/java/gravit/code/auth/jwt/JwtAuthFilter.java
  src/main/java/gravit/code/auth/jwt/JwtProvider.java
  src/main/java/gravit/code/auth/jwt/exception/CustomAccessDeniedHandler.java
  src/main/java/gravit/code/auth/jwt/exception/CustomAuthenticationEntryPoint.java
  src/main/java/gravit/code/auth/jwt/exception/CustomAuthenticationException.java
  src/main/java/gravit/code/auth/oauth/processor/OAuthLoginProcessor.java
  src/main/java/gravit/code/auth/oauth/service/OAuthClientService.java
  src/main/java/gravit/code/auth/util/RandomHandleGenerator.java
  src/main/java/gravit/code/domain/user/domain/User.java
  src/main/java/gravit/code/global/config/JpaAuditingConfig.java
  src/main/java/gravit/code/global/config/SecurityConfig.java
  src/main/java/gravit/code/global/exception/domain/CustomErrorCode.java
  src/test/java/gravit/code/auth/jwt/JwtProviderTest.java
  src/test/java/gravit/code/auth/util/RandomHandleGeneratorTest.java
  src/test/java/gravit/code/domain/learning/controller/LearningControllerTest.java
  src/test/java/gravit/code/domain/user/service/UserServiceTest.java
Labels: 🔨 Fix

#83 fix: 문제(SQL) 에 개행 추가
  src/main/resources/sql/004_gravit-problems.sql
Labels: 🔨 Fix
